// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtqPCHPsacounAlXVM4rzqZRx8wRkhs8k',
    appId: '1:72367843706:web:a5bd26e4dafe576a72cec3',
    messagingSenderId: '72367843706',
    projectId: 'invoice-generator-88fa5',
    authDomain: 'invoice-generator-88fa5.firebaseapp.com',
    storageBucket: 'invoice-generator-88fa5.firebasestorage.app',
    measurementId: 'G-G540ERZV7L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDky24kZZMyBqaM5RvxS_WGAklnkqfNu58',
    appId: '1:72367843706:ios:a1eec7c64566ae9872cec3',
    messagingSenderId: '72367843706',
    projectId: 'invoice-generator-88fa5',
    storageBucket: 'invoice-generator-88fa5.firebasestorage.app',
    iosBundleId: 'com.example.invoiceGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtqPCHPsacounAlXVM4rzqZRx8wRkhs8k',
    appId: '1:72367843706:web:6bb6988aa54f02b672cec3',
    messagingSenderId: '72367843706',
    projectId: 'invoice-generator-88fa5',
    authDomain: 'invoice-generator-88fa5.firebaseapp.com',
    storageBucket: 'invoice-generator-88fa5.firebasestorage.app',
    measurementId: 'G-HW72E6NSSY',
  );
}
